<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="58.040" tests="4" failures="3">
  <testsuite name="Root Suite" timestamp="2025-05-11T18:46:00" tests="0" file="cypress/e2e/features/schedule_enrollment.feature" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Schedule Enrollment" timestamp="2025-05-11T18:46:00" tests="4" time="58.003" failures="3">
    <testcase name="Schedule Enrollment Successfully enroll in a schedule" time="0.000" classname="Successfully enroll in a schedule">
      <failure message="expected 28 to be above 28" type="AssertionError"><![CDATA[AssertionError: expected 28 to be above 28
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/schedule_enrollment.feature:10744:40)

      + expected - actual

]]></failure>
    </testcase>
    <testcase name="Schedule Enrollment View enrolled schedules" time="6.542" classname="View enrolled schedules">
    </testcase>
    <testcase name="Schedule Enrollment Attempt to enroll in a full schedule" time="0.000" classname="Attempt to enroll in a full schedule">
      <failure message="Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `enrollAttempt`. No request ever occurred.

https://on.cypress.io/wait" type="CypressError"><![CDATA[CypressError: Timed out retrying after 5000ms: `cy.wait()` timed out waiting `5000ms` for the 1st request to the route: `enrollAttempt`. No request ever occurred.

https://on.cypress.io/wait
    at cypressErr (http://localhost:3001/__cypress/runner/cypress_runner.js:75187:18)
    at Object.errByPath (http://localhost:3001/__cypress/runner/cypress_runner.js:75242:10)
    at checkForXhr (http://localhost:3001/__cypress/runner/cypress_runner.js:134821:84)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:134844:28)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise.attempt.Promise.try (http://localhost:3001/__cypress/runner/cypress_runner.js:4315:29)
    at whenStable (http://localhost:3001/__cypress/runner/cypress_runner.js:143192:68)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:143133:14)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1701:18)
    at Promise._fulfill (http://localhost:3001/__cypress/runner/cypress_runner.js:1645:18)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:5450:46)
From Your Spec Code:
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/schedule_enrollment.feature:10784:12)
    at Registry.runStepDefininition (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/schedule_enrollment.feature:9255:48)
    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/schedule_enrollment.feature:10156:41)
    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/schedule_enrollment.feature:9860:36)
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/schedule_enrollment.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Schedule Enrollment Attempt to enroll in a schedule that conflicts with another enrolled schedule" time="0.000" classname="Attempt to enroll in a schedule that conflicts with another enrolled schedule">
      <failure message="Timed out retrying after 6000ms: Expected to find element: `[data-testid=&quot;schedule-start-time&quot;]`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 6000ms: Expected to find element: `[data-testid="schedule-start-time"]`, but never found it.
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/schedule_enrollment.feature:10803:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>