<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="8.816" tests="6" failures="1">
  <testsuite name="Root Suite" timestamp="2025-06-20T08:15:21" tests="0" file="cypress/e2e/features/assignment_grading.feature" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Assignment Grading and Feedback" timestamp="2025-06-20T08:15:21" tests="6" time="8.769" failures="2">
    <testcase name="Assignment Grading and Feedback Viewing all submissions for an assignment" time="0.000" classname="Viewing all submissions for an assignment">
      <failure message="Timed out retrying after 6000ms: Expected to find content: &apos;Software Engineering&apos; but never did." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 6000ms: Expected to find content: 'Software Engineering' but never did.
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_grading.feature:11429:35)
    at Registry.runStepDefininition (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_grading.feature:9255:48)
    at Object.fn (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_grading.feature:10156:41)
    at runStepWithLogGroup (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_grading.feature:9860:36)
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/e2e/features/assignment_grading.feature:10153:60)]]></failure>
    </testcase>
    <testcase name="Assignment Grading and Feedback &quot;after each&quot; hook for &quot;Viewing all submissions for an assignment&quot;" time="0.000" classname="&quot;after each&quot; hook for &quot;Viewing all submissions for an assignment&quot;">
      <failure message="`cy.request()` failed trying to load:

http://localhost:3000/test-utils/reset-database

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  &gt; Error: connect ECONNREFUSED 127.0.0.1:3000

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:3000/test-utils/reset-database

-----------------------------------------------------------

Common situations why this would fail:
  - you don&apos;t have internet access
  - you forgot to run / boot your web server
  - your web server isn&apos;t accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request

Because this error occurred during a `after each` hook we are skipping all of the remaining tests." type="CypressError"><![CDATA[CypressError: `cy.request()` failed trying to load:

http://localhost:3000/test-utils/reset-database

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > Error: connect ECONNREFUSED 127.0.0.1:3000

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:3000/test-utils/reset-database

-----------------------------------------------------------

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

https://on.cypress.io/request

Because this error occurred during a `after each` hook we are skipping all of the remaining tests.
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:132388:70)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at <unknown> (http://localhost:3001/__cypress/runner/cypress_runner.js:4203:37)
    at tryCatcher (http://localhost:3001/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (http://localhost:3001/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (http://localhost:3001/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (http://localhost:3001/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (http://localhost:3001/__cypress/runner/cypress_runner.js:1697:18)
    at _drainQueueStep (http://localhost:3001/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (http://localhost:3001/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (http://localhost:3001/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (http://localhost:3001/__cypress/tests?p=cypress/support/e2e.ts:13411:8)

From Node.js Internals:
  RequestError: Error: connect ECONNREFUSED 127.0.0.1:3000
      at new r (<embedded>:1868:354814)
      at ee.callback (<embedded>:1868:360815)
      at e.callback.s.callback [as _callback] (<embedded>:1868:360261)
      at s._callback.s.callback.s.callback (<embedded>:2086:91494)
      at ee.emit (node:events:527:28)
      at ee.onRequestError (<embedded>:2086:100436)
      at ClientRequest.emit (node:events:539:35)
      at Socket.socketErrorListener (node:_http_client:454:9)
      at Socket.emit (node:events:527:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:83:21)]]></failure>
    </testcase>
  </testsuite>
</testsuites>